apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-php-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-php
  template:
    metadata:
      labels:
        app: nginx-php
    spec:
      containers:
      - name: nginx
        image: rakshithavid/nginx-v1:latest
        ports:
        - containerPort: 80
      - name: php-fpm
        image: rakshithavid/php-v1:latest
        ports:
        - containerPort: 9000
